# Generated by Django 5.0.4 on 2024-04-08 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('content', 'Контент'), ('marketplace', 'Маркетплейс'), ('statistics', 'Статистика'), ('analytics', 'Аналитика'), ('promotion', 'Продвижение'), ('recommendations', 'Рекомендации'), ('feedback', 'Вопросы и отзывы'), ('prices_and_discounts', 'Цены и скидки'), ('universal', 'Универсальный')], max_length=25)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('lastusage', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=50)),
                ('longname', models.CharField(max_length=50)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('ogrn', models.CharField(max_length=15, unique=True)),
                ('address_registration', models.CharField(max_length=250)),
                ('registration_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('startjob', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=150)),
                ('shortfullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('address_registration', models.CharField(max_length=250)),
                ('address_residential', models.CharField(max_length=250)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('description', models.CharField(choices=[('content', 'Контент'), ('marketplace', 'Маркетплейс'), ('statistics', 'Статистика'), ('analytics', 'Аналитика'), ('promotion', 'Продвижение'), ('recommendations', 'Рекомендации'), ('feedback', 'Вопросы и отзывы'), ('prices_and_discounts', 'Цены и скидки'), ('universal', 'Универсальный')], max_length=25)),
                ('validity', models.DateField()),
                ('key', models.ForeignKey(default='Привязать API_KEY', on_delete=django.db.models.deletion.SET_DEFAULT, to='mainapp.apikey')),
            ],
        ),
        migrations.AddField(
            model_name='apikey',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.employe'),
        ),
        migrations.AddField(
            model_name='employe',
            name='individ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.individ'),
        ),
    ]
