# Generated by Django 5.0.4 on 2024-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_company_longname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='description',
            field=models.CharField(choices=[('content', 'Контент'), ('marketplace', 'Маркетплейс'), ('statistics', 'Статистика'), ('analytics', 'Аналитика'), ('promotion', 'Продвижение'), ('recommendations', 'Рекомендации'), ('feedback', 'Вопросы и отзывы'), ('prices_and_discounts', 'Цены и скидки'), ('universal', 'Универсальный')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apiurl',
            name='description',
            field=models.CharField(choices=[('supplies', 'Поставки'), ('stocks', 'Склады'), ('orders', 'Заказы'), ('sales', 'Продажи'), ('report_detail_by_period', 'Отчет о продажах по реализации'), ('cards_upload', 'Создание КТ'), ('cards_update', 'Редактирование КТ'), ('cards_upload_add', 'Добавление НМ к КТ'), ('cards_move_nm', 'Объединение / Разъединение НМ')], max_length=50),
        ),
    ]
