# Generated by Django 5.0.4 on 2024-04-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_apikey_description_alter_apiurl_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='apiurl',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
