# Generated by Django 5.0.4 on 2024-04-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_apikey_key_alter_apiurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiurl',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.apikey'),
        ),
    ]
