# Generated by Django 5.0.4 on 2024-04-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_apiurl_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiurl',
            name='key',
        ),
    ]
