# Generated by Django 5.0.4 on 2024-04-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_apiurl_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiurl',
            name='request',
            field=models.CharField(choices=[('GET', 'get'), ('POST', 'post'), ('PUT', 'put'), ('DELETE', 'delete'), ('PATCH', 'patch')], default='PUT', max_length=10),
        ),
        migrations.AlterField(
            model_name='apiurl',
            name='description',
            field=models.CharField(choices=[('supplies', 'Поставки'), ('stocks', 'Склады'), ('orders', 'Заказы'), ('sales', 'Продажи'), ('report_detail_by_period', 'Отчет о продажах по реализации'), ('cards_upload', 'Создание КТ'), ('cards_update', 'Редактирование КТ'), ('cards_upload_add', 'Добавление НМ к КТ'), ('feedbacks_unanswered', 'Необработанные отзывы'), ('new_feedbacks_questions', 'Непросмотренные отзывы и вопросы'), ('questions', 'Список вопросов'), ('questions_patch', 'Работа с вопросами'), ('feedbacks', 'Список отзывов'), ('feedbacks_patch', 'Работа с отзывом'), ('feedbacks_excel', 'Получение отзывов в формате XLSX')], max_length=50),
        ),
    ]
