# Generated by Django 5.0.4 on 2024-04-10 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0007_apiurl_request_alter_apiurl_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizationreport_id', models.PositiveBigIntegerField(help_text='Номер отчёта', unique=True, verbose_name='№ отчета')),
                ('date_from', models.DateField(help_text='Дата начала отчётного периода', verbose_name='Дата начала')),
                ('date_to', models.DateField(help_text='Дата конца отчётного периода', verbose_name='Дата конца')),
                ('create_dt', models.DateField(help_text='Дата формирования отчёта', verbose_name='Дата формирования')),
                ('sales', models.DecimalField(decimal_places=2, help_text='Выручка с учетом возвратов', max_digits=15, verbose_name='Продажа')),
                ('transfer_for_goods', models.DecimalField(decimal_places=2, help_text='Выручка за вычетом комиссии', max_digits=15, verbose_name='К перечислению за товар')),
                ('logistic', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость логистики')),
                ('penalty_logistic', models.IntegerField(verbose_name='Штраф. Повышенная логистика согласно коэффициенту по обмерам')),
                ('penalty_other', models.IntegerField(verbose_name='Другие виды штрафов')),
                ('penalty', models.IntegerField(verbose_name='Общая сумма штрафов')),
                ('additional_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доплаты')),
                ('storage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость хранения')),
                ('acceptance', models.IntegerField(verbose_name='Стоимость платной приемки')),
                ('deduction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прочие удержания/выплаты')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Итого к оплате')),
                ('currency', models.CharField(max_length=5, verbose_name='Валюта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.company')),
            ],
            options={
                'ordering': ['-create_dt', 'company'],
            },
        ),
        migrations.CreateModel(
            name='RealizationReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrd_id', models.PositiveBigIntegerField(help_text='Номер строки', verbose_name='Номер строки')),
                ('gi_id', models.PositiveIntegerField(help_text='Номер поставки', verbose_name='Номер поставки')),
                ('subject_name', models.CharField(help_text='Предмет', max_length=150, verbose_name='Предмет')),
                ('nm_id', models.PositiveIntegerField(help_text='Артикул WB', verbose_name='Код номенклатуры')),
                ('brand_name', models.CharField(help_text='Бренд', max_length=50, verbose_name='Бренд')),
                ('sa_name', models.CharField(help_text='Артикул продавца', max_length=150, verbose_name='Артикул поставщика')),
                ('ts_name', models.CharField(help_text='Размер', max_length=15, verbose_name='Размер')),
                ('barcode', models.CharField(help_text='Баркод', max_length=15, verbose_name='Баркод')),
                ('doc_type_name', models.CharField(help_text='Тип документа', max_length=10, verbose_name='Тип документа')),
                ('quantity', models.PositiveSmallIntegerField(help_text='Количество', verbose_name='Кол-во')),
                ('retail_price', models.DecimalField(decimal_places=2, help_text='Цена розничная', max_digits=7, verbose_name='Цена розничная')),
                ('retail_amount', models.DecimalField(decimal_places=2, help_text='Сумма продаж (возвратов)', max_digits=7, verbose_name='Вайлдберриз реализовал Товар (Пр)')),
                ('office_name', models.CharField(help_text='Склад', max_length=50, verbose_name='Склад')),
                ('supplier_oper_name', models.CharField(help_text='Обоснование для оплаты', max_length=50, verbose_name='Обоснование для оплаты')),
                ('order_dt', models.DateField(help_text='Дата заказа', verbose_name='Дата заказа покупателем')),
                ('sale_dt', models.DateField(help_text='Дата продажи', verbose_name='Дата продажи')),
                ('shk_id', models.PositiveBigIntegerField(help_text='Штрих-код', verbose_name='ШК')),
                ('delivery_amount', models.PositiveSmallIntegerField(help_text='Количество доставок', verbose_name='Количество доставок')),
                ('return_amount', models.PositiveSmallIntegerField(help_text='Количество возвратов', verbose_name='Количество возврата')),
                ('delivery_rub', models.DecimalField(decimal_places=2, help_text='Стоимость логистики', max_digits=7, verbose_name='Услуги по доставке товара покупателю')),
                ('gi_box_type_name', models.CharField(help_text='Тип коробов', max_length=15, verbose_name='Тип коробов')),
                ('ppvz_for_pay', models.DecimalField(decimal_places=2, help_text='К перечислению продавцу за реализованный товар', max_digits=7, verbose_name='К перечислению Продавцу за реализованный Товар')),
                ('site_country', models.CharField(help_text='Страна продажи', max_length=30, verbose_name='Страна')),
                ('penalty', models.PositiveIntegerField(help_text='Штрафы', verbose_name='Общая сумма штрафов')),
                ('additional_payment', models.DecimalField(decimal_places=2, help_text='Доплаты', max_digits=7, verbose_name='Доплаты')),
                ('storage_fee', models.DecimalField(decimal_places=2, help_text='Стоимость хранения', max_digits=10, verbose_name='Хранение')),
                ('deduction', models.DecimalField(decimal_places=2, help_text='Прочие удержания/выплаты', max_digits=10, verbose_name='Удержания')),
                ('acceptance', models.IntegerField(help_text='Стоимость платной приёмки', verbose_name='Платная приемка')),
                ('realizationReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsalesapp.realizationreport')),
            ],
        ),
    ]
