# Generated by Django 5.0.4 on 2024-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsalesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizationreport',
            name='create_dt',
            field=models.DateTimeField(help_text='Дата формирования отчёта', verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='realizationreport',
            name='date_from',
            field=models.DateTimeField(help_text='Дата начала отчётного периода', verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='realizationreport',
            name='date_to',
            field=models.DateTimeField(help_text='Дата конца отчётного периода', verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='order_dt',
            field=models.DateTimeField(help_text='Дата заказа', verbose_name='Дата заказа покупателем'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='sale_dt',
            field=models.DateTimeField(help_text='Дата продажи', verbose_name='Дата продажи'),
        ),
    ]
