# Generated by Django 5.0.4 on 2024-04-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsalesapp', '0004_remove_realizationreportdetail_rrd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='acceptance',
            field=models.IntegerField(default=None, help_text='Стоимость платной приёмки', verbose_name='Платная приемка'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Прочие удержания/выплаты', max_digits=10, verbose_name='Удержания'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='storage_fee',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Стоимость хранения', max_digits=10, verbose_name='Хранение'),
        ),
    ]
