# Generated by Django 5.0.4 on 2024-04-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsalesapp', '0007_alter_realizationreportdetail_doc_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='acceptance',
            field=models.IntegerField(help_text='Стоимость платной приёмки', verbose_name='Платная приемка'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='deduction',
            field=models.DecimalField(decimal_places=2, help_text='Прочие удержания/выплаты', max_digits=10, verbose_name='Удержания'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='doc_type_name',
            field=models.CharField(default=None, help_text='Тип документа', max_length=10, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='storage_fee',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость хранения', max_digits=10, verbose_name='Хранение'),
        ),
    ]
