# Generated by Django 5.0.4 on 2024-04-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsalesapp', '0011_alter_realizationreportdetail_doc_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='doc_type_name',
            field=models.CharField(help_text='Тип документа', max_length=10, null=True, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='gi_box_type_name',
            field=models.CharField(help_text='Тип коробов', max_length=15, null=True, verbose_name='Тип коробов'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='office_name',
            field=models.CharField(help_text='Склад', max_length=50, null=True, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='site_country',
            field=models.CharField(help_text='Страна продажи', max_length=30, null=True, verbose_name='Страна'),
        ),
    ]
