# Generated by Django 5.0.4 on 2024-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsalesapp', '0012_alter_realizationreportdetail_doc_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='barcode',
            field=models.CharField(default='', help_text='Баркод', max_length=15, verbose_name='Баркод'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='brand_name',
            field=models.CharField(default='', help_text='Бренд', max_length=50, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='doc_type_name',
            field=models.CharField(default='', help_text='Тип документа', max_length=10, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='gi_box_type_name',
            field=models.CharField(default='', help_text='Тип коробов', max_length=15, verbose_name='Тип коробов'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='office_name',
            field=models.CharField(default='', help_text='Склад', max_length=50, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='sa_name',
            field=models.CharField(default='', help_text='Артикул продавца', max_length=150, verbose_name='Артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='site_country',
            field=models.CharField(default='', help_text='Страна продажи', max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='subject_name',
            field=models.CharField(default='', help_text='Предмет', max_length=150, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='supplier_oper_name',
            field=models.CharField(default='', help_text='Обоснование для оплаты', max_length=50, verbose_name='Обоснование для оплаты'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='ts_name',
            field=models.CharField(default='', help_text='Размер', max_length=15, verbose_name='Размер'),
        ),
    ]
