# Generated by Django 5.0.4 on 2024-04-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsalesapp', '0013_alter_realizationreportdetail_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='order_dt',
            field=models.DateField(help_text='Дата заказа', verbose_name='Дата заказа покупателем'),
        ),
        migrations.AlterField(
            model_name='realizationreportdetail',
            name='sale_dt',
            field=models.DateField(help_text='Дата продажи', verbose_name='Дата продажи'),
        ),
    ]
