# Generated by Django 5.0.4 on 2024-04-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsalesapp', '0016_alter_realizationreportdetail_acceptance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizationreport',
            name='status',
            field=models.BooleanField(default=False, help_text='Статус отражения в главном отчете', verbose_name='Главный отчет'),
        ),
    ]
