"""
Django settings for goodseller project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%_bteaol!4j6!qdzr#wq30@*vxa-ut-*vy&9mexz#pq2swrdx2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
    'reportsalesapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'goodseller.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goodseller.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join('BASE_DIR', 'static')
STATICFILES_DIR = []

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': './log/django.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'reportsalesapp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

API_DESCRIPTION_CHOICES = (
    ('content', 'Контент'),
    ('marketplace', 'Маркетплейс'),
    ('statistics', 'Статистика'),
    ('analytics', 'Аналитика'),
    ('promotion', 'Продвижение'),
    ('recommendations', 'Рекомендации'),
    ('feedback', 'Вопросы и отзывы'),
    ('prices_and_discounts', 'Цены и скидки'),
    ('universal', 'Универсальный'),
)

URL_DESCRIPTION_CHOICES = (
    ('supplies', 'Поставки'),
    ('stocks', 'Склады'),
    ('orders', 'Заказы'),
    ('sales', 'Продажи'),
    ('report_detail_by_period', 'Отчет о продажах по реализации'),
    ('cards_upload', 'Создание КТ'),
    ('cards_update', 'Редактирование КТ'),
    ('cards_upload_add', 'Добавление НМ к КТ'),
    ('feedbacks_unanswered', 'Необработанные отзывы'),
    ('new_feedbacks_questions', 'Непросмотренные отзывы и вопросы'),
    ('questions', 'Список вопросов'),
    ('questions_patch', 'Работа с вопросами'),
    ('feedbacks', 'Список отзывов'),
    ('feedbacks_patch', 'Работа с отзывом'),
    ('feedbacks_excel', 'Получение отзывов в формате XLSX'),
)

REQUEST_TYPES_CHOICES = (
    ('GET', 'get'),
    ('POST', 'post'),
    ('PUT', 'put'),
    ('DELETE', 'delete'),
    ('PATCH', 'patch'),
)
